#!/usr/bin/env node
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    fnv1a,
    forgeAsset,
    normalizeHex,
    orphanPixels,
    stableStringify,
    validateTileEdges,
} from '../src/render/pixelForgeCore.js';
import { BITMAP_ASSETS, RUNTIME_VISUAL_IDS, TILE_ASSETS, VISUALS } from '../src/render/visualManifest.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contractPath = join(root, 'art/pixel-style.json');
const generatedJsPath = join(root, 'src/render/artTokens.generated.js');
const generatedCssPath = join(root, 'src/style.tokens.generated.css');
const generatedManifestPath = join(root, 'art/generated/pixel-manifest.generated.json');

async function loadContract() {
    return JSON.parse(await readFile(contractPath, 'utf8'));
}

function kebab(value) {
    return value.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
}

function generatedTokens(contract) {
    const tokenData = { palette: contract.palette, rhythm: contract.rhythm };
    const js = `// Generated by tools/pixel-forge.mjs. Do not edit by hand.\nexport const ART_TOKENS = Object.freeze(${JSON.stringify(tokenData, null, 4)});\n`;
    const cssLines = [
        '/* Generated by tools/pixel-forge.mjs. Do not edit by hand. */',
        ':root {',
        ...Object.entries(contract.palette)
            .filter(([, value]) => value.length !== 9)
            .map(([name, value]) => `    --art-${kebab(name)}: ${value};`),
        ...Object.entries(contract.rhythm)
            .map(([name, value]) => `    --art-${kebab(name)}: ${value};`),
        '}',
        '',
    ];
    return { js, css: cssLines.join('\n') };
}

function forgeAll() {
    return BITMAP_ASSETS.map(recipe => forgeAsset(recipe));
}

function generatedManifest(contract, assets) {
    const entries = assets.map(asset => ({
        id: asset.id,
        width: asset.width,
        height: asset.height,
        anchor: asset.anchor,
        hash: asset.hash,
    })).sort((a, b) => a.id.localeCompare(b.id));
    return `${JSON.stringify({
        version: contract.version,
        logicalPixelWorldPx: contract.logicalPixelWorldPx,
        contractHash: fnv1a(stableStringify(contract)),
        assets: entries,
    }, null, 2)}\n`;
}

async function sourceFiles(directory) {
    const result = [];
    for(const entry of await readdir(directory, { withFileTypes: true })) {
        const path = join(directory, entry.name);
        if(entry.isDirectory()) result.push(...await sourceFiles(path));
        else if(entry.isFile() && path.endsWith('.js')) result.push(path);
    }
    return result;
}

async function validateStaticRenderGate() {
    const errors = [];
    const forbidden = /\.(?:fillRect|strokeRect|clearRect|drawImage|fillText|strokeText|arc|ellipse|createLinearGradient)\s*\(|\.(?:fillStyle|strokeStyle)\s*=/;
    for(const path of await sourceFiles(join(root, 'src'))) {
        const rel = relative(root, path);
        if(rel.startsWith('src/render/')) continue;
        const lines = (await readFile(path, 'utf8')).split('\n');
        lines.forEach((line, index) => {
            if(forbidden.test(line)) errors.push(`${rel}:${index + 1}: ad-hoc Canvas visual drawing`);
        });
    }
    return errors;
}

async function validate() {
    const contract = await loadContract();
    const errors = [];
    const allowed = new Set(Object.values(contract.palette).map(normalizeHex));
    const assets = forgeAll();

    if(contract.logicalPixelWorldPx !== 4) errors.push('logical pixel must remain 4 world px');
    if(new Set(RUNTIME_VISUAL_IDS).size !== RUNTIME_VISUAL_IDS.length) errors.push('duplicate runtime visual IDs');
    for(const id of RUNTIME_VISUAL_IDS) {
        if(!VISUALS[id]) errors.push(`${id}: unregistered runtime visual ID`);
    }
    for(const recipe of BITMAP_ASSETS) {
        const asset = assets.find(candidate => candidate.id === recipe.id);
        if(!recipe.nearestNeighbor) errors.push(`${recipe.id}: nearest-neighbor policy missing`);
        for(const color of Object.values(recipe.semanticColors)) {
            if(!allowed.has(normalizeHex(color))) errors.push(`${recipe.id}: color ${color} is outside the allowed palette`);
        }
        for(let index = 3; index < asset.pixels.length; index += 4) {
            if(asset.pixels[index] !== 0 && asset.pixels[index] !== 255) {
                errors.push(`${recipe.id}: non-binary alpha ${asset.pixels[index]}`);
                break;
            }
        }
        if(recipe.noOrphans && orphanPixels(asset).length) errors.push(`${recipe.id}: orphan pixels detected`);
        if(asset.width !== recipe.width || asset.height !== recipe.height) errors.push(`${recipe.id}: generated dimensions changed`);
        if(asset.anchor.some(value => value < 0 || value > 1)) errors.push(`${recipe.id}: invalid normalized anchor`);
        if(forgeAsset(recipe).hash !== asset.hash) errors.push(`${recipe.id}: nondeterministic output hash`);
    }
    errors.push(...validateTileEdges(TILE_ASSETS));
    errors.push(...await validateStaticRenderGate());

    const { js, css } = generatedTokens(contract);
    const manifest = generatedManifest(contract, assets);
    for(const [path, expected] of [[generatedJsPath, js], [generatedCssPath, css], [generatedManifestPath, manifest]]) {
        let actual = '';
        try { actual = await readFile(path, 'utf8'); } catch {}
        if(actual !== expected) errors.push(`${relative(root, path)}: generated output is stale`);
    }

    if(errors.length) throw new Error(`Pixel Forge validation failed:\n${errors.map(error => `- ${error}`).join('\n')}`);
    return assets;
}

async function generate() {
    const contract = await loadContract();
    const assets = forgeAll();
    const { js, css } = generatedTokens(contract);
    await mkdir(dirname(generatedManifestPath), { recursive: true });
    await writeFile(generatedJsPath, js);
    await writeFile(generatedCssPath, css);
    await writeFile(generatedManifestPath, generatedManifest(contract, assets));
    return assets;
}

const command = process.argv[2] || 'validate';
try {
    const assets = command === 'generate' ? await generate() : await validate();
    const aggregateHash = fnv1a(assets.map(asset => `${asset.id}:${asset.hash}`).join('|'));
    console.log(`Pixel Forge ${command}: ${assets.length} assets, ${RUNTIME_VISUAL_IDS.length} visual IDs, hash ${aggregateHash}`);
} catch(error) {
    console.error(error.message);
    process.exitCode = 1;
}
